import type { Metadata } from "next";
import LegalLayout from "@/components/site/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Restenzo collects, uses, stores and protects your data.",
};

const Section: React.FC<{
  id?: string;
  title: string;
  children: React.ReactNode;
}> = ({ id, title, children }) => (
  <section id={id} className="scroll-mt-28">
    <h2 className="text-xl font-bold text-gray-900 dark:text-white">
      {title}
    </h2>
    <div className="mt-3 space-y-3 text-sm">{children}</div>
  </section>
);

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="April 21, 2026">
      <p className="text-base">
        This Privacy Policy explains how Restenzo (“we”, “us”, “our”) collects,
        uses and shares information in connection with our restaurant
        management platform. By using Restenzo you agree to this policy.
      </p>

      <Section title="Information we collect">
        <p>
          We collect information you provide when you create an account, add
          restaurants and branches, configure menus, take orders, process
          payments and communicate with us. This may include names, email
          addresses, restaurant details, staff roles and transactional data
          generated by your operations.
        </p>
      </Section>

      <Section title="How we use information">
        <p>
          We use your information to operate and improve Restenzo, provide
          customer support, secure our platform, communicate with you, and
          comply with legal obligations. We do not sell your data to third
          parties.
        </p>
      </Section>

      <Section title="Data sharing">
        <p>
          We share information with trusted service providers who help us run
          Restenzo for example cloud hosting, email delivery and payment
          processing (such as Stripe). These providers are contractually bound
          to protect your information.
        </p>
      </Section>

      <Section id="security" title="Security">
        <p>
          We use industry-standard encryption in transit and at rest,
          role based access controls and audit logs. While no system is 100%
          impenetrable, we take every reasonable measure to keep your data
          safe.
        </p>
      </Section>

      <Section id="cookies" title="Cookies">
        <p>
          Restenzo uses cookies and similar technologies to keep you signed in,
          remember preferences and measure product usage. You can control
          cookies through your browser settings.
        </p>
      </Section>

      <Section title="Your rights">
        <p>
          Depending on where you live, you may have the right to access,
          correct, delete or export your personal information. To exercise any
          of these rights, email{" "}
          <a href="mailto:privacy@restenzo.com" className="text-[#ff5a1f] hover:underline">
            privacy@restenzo.com
          </a>
          .
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions? Write to us at{" "}
          <a href="mailto:privacy@restenzo.com" className="text-[#ff5a1f] hover:underline">
            privacy@restenzo.com
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  );
}
