"use client";

import type { Printer } from "@/types/printer";

/**
 * Mock printer data for Printers Management UI.
 * Replace with API fetch when backend is ready.
 */
export const MOCK_PRINTERS: Printer[] = [
  {
    id: "p1",
    name: "Counter Receipt Printer",
    type: "receipt",
    branchId: 1,
    branchName: "Main Branch",
    assignedArea: "Cash Counter",
    connectionType: "usb",
    paperSize: "80mm",
    status: "active",
    assignedPurposes: ["receipts"],
    autoPrintReceipts: true,
    autoPrintKitchenTickets: false,
    autoPrintInvoices: false,
  },
  {
    id: "p2",
    name: "Kitchen Printer 1",
    type: "kitchen",
    branchId: 1,
    branchName: "Main Branch",
    assignedArea: "Main Kitchen",
    connectionType: "network",
    ipAddress: "192.168.1.45",
    port: 9100,
    paperSize: "80mm",
    status: "active",
    assignedPurposes: ["kitchen_orders"],
    autoPrintReceipts: false,
    autoPrintKitchenTickets: true,
    autoPrintInvoices: false,
  },
  {
    id: "p3",
    name: "BBQ Printer",
    type: "kitchen",
    branchId: 2,
    branchName: "Super Branch",
    assignedArea: "BBQ Station",
    connectionType: "network",
    ipAddress: "192.168.1.52",
    port: 9100,
    paperSize: "80mm",
    status: "active",
    assignedPurposes: ["kitchen_orders"],
    autoPrintReceipts: false,
    autoPrintKitchenTickets: true,
    autoPrintInvoices: false,
  },
  {
    id: "p4",
    name: "Drinks Printer",
    type: "bar",
    branchId: 1,
    branchName: "Main Branch",
    assignedArea: "Drinks Station",
    connectionType: "usb",
    paperSize: "58mm",
    status: "inactive",
    assignedPurposes: ["drinks_orders"],
    autoPrintReceipts: false,
    autoPrintKitchenTickets: false,
    autoPrintInvoices: false,
  },
  {
    id: "p5",
    name: "Billing Printer",
    type: "invoice",
    branchId: 1,
    branchName: "Main Branch",
    assignedArea: "Front Desk",
    connectionType: "network",
    ipAddress: "192.168.1.60",
    port: 9100,
    paperSize: "80mm",
    status: "offline",
    assignedPurposes: ["invoices"],
    autoPrintReceipts: false,
    autoPrintKitchenTickets: false,
    autoPrintInvoices: true,
  },
];
